language: node_js
node_js:
    - "8.9.0"
install:
    - npm install
before_script:
    - npm client:http-server -- --silent &
script:
    - npm run check
    - npm run client:dist
    - npm run client:functional
